### ISSUE TITLE
Slow loading page

### ISSUE THREAD

**Issue by ramolec** [BWibo/nextcloud-compose#1]
Hi Bwibo, 

Did you have a problem with slow page loading?

I did a test with your compose and I'm having a slow loading of pages. Do you feel with that in your stack too?

Or did you do some configuration for it? I'm running exactly like your config on a VPS (3vcpu, 8gb ram), just these containers.

**Comment by BWibo** [comment]
Hey there, 
can you be a bit more precise what you mean by "slow"?

Which pages are loading in what time? I'm running this stack on an RaspberryPI4 from an external USB3 HDD and the pages are loading fine. The is stack are using the default settings of Nextcloud and I did not add any specific config.

If you feel that image previews are loading slow, I can recommend this:

* https://apps.nextcloud.com/apps/previewgenerator
* [Blog entry on how to configre this](https://rayagainstthemachine.net/linux%20administration/nextcloud-photos/)

**Comment by BWibo** [comment]
Closing due to missing feedback.
